#!/bin/bash

# ===================================
# 🔍 Script per trovare l'IP del Mac
# ===================================

echo "🔍 Cercando informazioni di rete..."
echo ""

# 1. Nome mDNS (Bonjour)
echo "📡 Nome mDNS (Bonjour):"
HOSTNAME=$(hostname)
echo "   $HOSTNAME"
echo "   Usa in .env: EXPO_PUBLIC_BACKEND_URL=http://$HOSTNAME:3000"
echo ""

# 2. IP WiFi
echo "📶 IP WiFi:"
WIFI_IP=$(ifconfig en0 2>/dev/null | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}')
if [ -n "$WIFI_IP" ]; then
    echo "   $WIFI_IP"
    echo "   Usa in .env: EXPO_PUBLIC_BACKEND_URL=http://$WIFI_IP:3000"
else
    echo "   ❌ Non connesso al WiFi"
fi
echo ""

# 3. IP Ethernet
echo "🔌 IP Ethernet:"
ETH_IP=$(ifconfig en1 2>/dev/null | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}')
if [ -n "$ETH_IP" ]; then
    echo "   $ETH_IP"
    echo "   Usa in .env: EXPO_PUBLIC_BACKEND_URL=http://$ETH_IP:3000"
else
    echo "   ❌ Non connesso via Ethernet"
fi
echo ""

# 4. Tutti gli IP
echo "🌐 Tutti gli IP del Mac:"
ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print "   "$2}'
echo ""

# 5. Subnet
if [ -n "$WIFI_IP" ]; then
    SUBNET=$(echo $WIFI_IP | cut -d. -f1-3)
    echo "📡 Subnet WiFi: $SUBNET.x"
    echo "   Il telefono deve essere su questa subnet per connettersi"
    echo ""
fi

# 6. Consiglio
echo "💡 CONSIGLIO:"
echo "   Per sviluppo usa mDNS: http://$HOSTNAME:3000"
echo "   È più affidabile perché funziona anche se cambi rete WiFi!"
echo ""

# 7. Test porta 3000
echo "🔍 Testando se il backend è avviato sulla porta 3000..."
if lsof -i :3000 >/dev/null 2>&1; then
    echo "   ✅ Backend attivo sulla porta 3000"
else
    echo "   ❌ Nessun processo sulla porta 3000"
    echo "   Avvia il backend con: cd WellnessCoach/backend && npm run dev"
fi
echo ""

# 8. Crea file .env se non esiste
if [ ! -f "mobile/.env" ]; then
    echo "📝 Creando mobile/.env con configurazione automatica..."
    cat > mobile/.env <<EOF
# Auto-generated by get-mac-ip.sh
# Usa mDNS per massima compatibilità
EXPO_PUBLIC_BACKEND_URL=http://$HOSTNAME:3000

# Alternative (decommenta per usare):
# EXPO_PUBLIC_BACKEND_URL=http://$WIFI_IP:3000  # IP WiFi
# EXPO_PUBLIC_BACKEND_URL=  # Auto-discovery
EOF
    echo "   ✅ File mobile/.env creato"
else
    echo "📝 File mobile/.env già esistente, non modificato"
fi
echo ""

echo "✅ Fatto! Usa una delle configurazioni sopra nel file mobile/.env"

