-- Add ai_analysis_text to emotion_analyses table to store generated AI insights
ALTER TABLE emotion_analyses
ADD COLUMN IF NOT EXISTS ai_analysis_text TEXT;

COMMENT ON COLUMN emotion_analyses.ai_analysis_text IS 'Text output generated by AI for this analysis (e.g. insights or observations)';
